// frontend/src/components/form/GenderField/GenderField.tsx
import classNames from "classnames";
import Label from "../../@common/Label/Label";
import Radio from "../../@common/Radio/Radio";
import styles from "./GenderField.module.css";

type GenderFieldProps = {
  className?: string;
  required?: boolean;
  value: "MALE" | "FEMALE";
  onChange: React.ChangeEventHandler<HTMLInputElement>;
};

const GenderField = ({ className, required = false, value, onChange }: GenderFieldProps) => {
  return (
    <div className={classNames(styles["gender-field"], className)}>
      <Label className={styles.label} required={required}>
        성별
      </Label>
      <div className={styles["gender-group"]}>
        <Radio
          onChange={onChange}
          name="gender"
          label="남자"
          value="MALE"
          checked={value === "MALE"}
          required={required}
        />
        <Radio
          onChange={onChange}
          name="gender"
          label="여자"
          value="FEMALE"
          checked={value === "FEMALE"}
          required={required}
        />
      </div>
    </div>
  );
};

export default GenderField;

// frontend/src/components/form/GenderField.vue
<template>
  <Field class="gender-field">
    <Label required>성별</Label>
    <div class="gender-group">
      <Radio name="gender" label="남자" value="male" v-model="gender" required />
      <Radio name="gender" label="여자" value="female" v-model="gender" required />
    </div>
  </Field>
</template>

<script>
import Label from "./Label"
import Field from "./Field"
import Radio from "./Radio"

const GenderField = {
  components: {
    Label,
    Field,
    Radio,
  },
  props: {
    value: String,
  },
  data: () => ({
    gender: "",
  }),
  watch: {
    gender() {
      this.$emit("input", this.gender)
    },
  },
  created() {
    this.gender = this.value
  },
}

export default GenderField
</script>

<style scoped>
.gender-group {
  display: flex;
  margin-right: 10px;
  font-size: 0.8em;
}
</style>
